import { v4 as uuidv4 } from "uuid";
export default [
  {
    id: uuidv4(),
    name: "Kilimanjaro",
    height: 5895,
    country: "Tanzania"
  },
  { id: uuidv4(), name: "Everest", height: 8848, country: "Nepal" },
  { id: uuidv4(), name: "Mount Fuji", height: 3776, country: "Japan" },
  { id: uuidv4(), name: "Mont Blanc", height: 4808, country: "Italy/France" },
  { id: uuidv4(), name: "Vaalserberg", height: 323, country: "Netherlands" },
  { id: uuidv4(), name: "Denali", height: 6168, country: "United States" },
  { id: uuidv4(), name: "Popocatepetl", height: 5465, country: "Mexico" },
  { id: uuidv4(), name: "Kilimanjaro", height: 5895, country: "Tanzania" },
  { id: uuidv4(), name: "Everest", height: 8848, country: "Nepal" },
  { id: uuidv4(), name: "Mount Fuji", height: 3776, country: "Japan" },
  { id: uuidv4(), name: "Mont Blanc", height: 4808, country: "Italy/France" },
  { id: uuidv4(), name: "Vaalserberg", height: 323, country: "Netherlands" },
  { id: uuidv4(), name: "Denali", height: 6168, country: "United States" },
  { id: uuidv4(), name: "Popocatepetl", height: 5465, country: "Mexico" },
  { id: uuidv4(), name: "Kilimanjaro", height: 5895, country: "Tanzania" },
  { id: uuidv4(), name: "Everest", height: 8848, country: "Nepal" },
  { id: uuidv4(), name: "Mount Fuji", height: 3776, country: "Japan" },
  { id: uuidv4(), name: "Mont Blanc", height: 4808, country: "Italy/France" },
  { id: uuidv4(), name: "Vaalserberg", height: 323, country: "Netherlands" },
  { id: uuidv4(), name: "Denali", height: 6168, country: "United States" },
  { id: uuidv4(), name: "Popocatepetl", height: 5465, country: "Mexico" },
  { id: uuidv4(), name: "Kilimanjaro", height: 5895, country: "Tanzania" },
  { id: uuidv4(), name: "Everest", height: 8848, country: "Nepal" },
  { id: uuidv4(), name: "Mount Fuji", height: 3776, country: "Japan" },
  { id: uuidv4(), name: "Mont Blanc", height: 4808, country: "Italy/France" },
  { id: uuidv4(), name: "Vaalserberg", height: 323, country: "Netherlands" },
  { id: uuidv4(), name: "Denali", height: 6168, country: "United States" },
  { id: uuidv4(), name: "Popocatepetl", height: 5465, country: "Mexico" },
  { id: uuidv4(), name: "Kilimanjaro", height: 5895, country: "Tanzania" },
  { id: uuidv4(), name: "Everest", height: 8848, country: "Nepal" },
  { id: uuidv4(), name: "Mount Fuji", height: 3776, country: "Japan" },
  { id: uuidv4(), name: "Mont Blanc", height: 4808, country: "Italy/France" },
  { id: uuidv4(), name: "Vaalserberg", height: 323, country: "Netherlands" },
  { id: uuidv4(), name: "Denali", height: 6168, country: "United States" },
  { id: uuidv4(), name: "Popocatepetl", height: 5465, country: "Mexico" },
  { id: uuidv4(), name: "Kilimanjaro", height: 5895, country: "Tanzania" },
  { id: uuidv4(), name: "Everest", height: 8848, country: "Nepal" },
  { id: uuidv4(), name: "Mount Fuji", height: 3776, country: "Japan" },
  { id: uuidv4(), name: "Mont Blanc", height: 4808, country: "Italy/France" },
  { id: uuidv4(), name: "Vaalserberg", height: 323, country: "Netherlands" },
  { id: uuidv4(), name: "Denali", height: 6168, country: "United States" },
  { id: uuidv4(), name: "Popocatepetl", height: 5465, country: "Mexico" },
  { id: uuidv4(), name: "Kilimanjaro", height: 5895, country: "Tanzania" },
  { id: uuidv4(), name: "Everest", height: 8848, country: "Nepal" },
  { id: uuidv4(), name: "Mount Fuji", height: 3776, country: "Japan" },
  { id: uuidv4(), name: "Mont Blanc", height: 4808, country: "Italy/France" },
  { id: uuidv4(), name: "Vaalserberg", height: 323, country: "Netherlands" },
  { id: uuidv4(), name: "Denali", height: 6168, country: "United States" },
  { id: uuidv4(), name: "Popocatepetl", height: 5465, country: "Mexico" }
];
